package com.krstock.v3.data.model

/**
 * Source-backed quantitative snapshot generated by scripts/collect_real_quant.py.
 * Null means the metric was not verifiably available; it must never be replaced by a guessed value.
 */
data class RealQuantRecord(
    val code: String,
    val m01Raw: Double?,
    val m01Percentile: Double?,
    val m01ReasonCode: String?,
    val m01Basis: String,
    val m02Raw: Double?,
    val m02Percentile: Double?,
    val m02ReasonCode: String?,
    val m02Basis: String,
    val m03Raw: Double?,
    val m03Percentile: Double?,
    val m03ReasonCode: String?,
    val m03Basis: String,
    val m04Raw: Double?,
    val m04Percentile: Double?,
    val m04ReasonCode: String?,
    val m04Basis: String,
    val compositeScore: Double?,
    val rankOrder: Int?
)
