package com.krstock.v3.data.stage

import com.krstock.v3.data.model.FinancialSafetyRecord
import com.krstock.v3.data.model.FinancialSafetySnapshot
import com.krstock.v3.data.model.FinancialSafetyStatus
import com.krstock.v3.data.model.MetricValue
import com.krstock.v3.data.model.ValuationBand
import com.krstock.v3.data.repository.StockRepository
import org.json.JSONObject
import kotlin.math.abs

/**
 * Parser for the top-level financial_safety section generated by
 * scripts/collect_financial_safety.py. The entire section is rejected when its
 * policy, date, identity set, coverage accounting, or numeric invariants differ
 * from the active quant snapshot.
 */
object FinancialSafetySnapshotParser {
    const val POLICY_VERSION = "STAGE4_BS_SAFETY_V1"
    private const val DEBT_TO_EQUITY_MAX = 400.0
    private const val CURRENT_RATIO_MIN = 70.0
    private const val IDENTITY_TOLERANCE = 5.0

    fun parse(
        safety: JSONObject,
        expectedSnapshotDate: String,
        expectedCodes: Set<String>,
    ): FinancialSafetySnapshot {
        require(safety.getInt("schema_version") == 1) { "unexpected financial-safety schema" }
        require(safety.getString("policy_version") == POLICY_VERSION) { "unexpected financial-safety policy" }
        require(safety.getString("snapshot_date_kst") == expectedSnapshotDate) { "financial-safety snapshot mismatch" }

        val source = safety.getString("source")
        val sourceFile = safety.getString("source_file")
        require(source.isNotBlank()) { "financial-safety source missing" }
        require(sourceFile.isNotBlank()) { "financial-safety source file missing" }

        val thresholds = safety.getJSONObject("thresholds")
        require(abs(thresholds.getDouble("debt_to_equity_max_pct") - DEBT_TO_EQUITY_MAX) < 1e-9) {
            "financial-safety debt threshold mismatch"
        }
        require(abs(thresholds.getDouble("current_ratio_min_pct") - CURRENT_RATIO_MIN) < 1e-9) {
            "financial-safety current-ratio threshold mismatch"
        }
        require(abs(thresholds.getDouble("accounting_identity_tolerance_pct") - IDENTITY_TOLERANCE) < 1e-9) {
            "financial-safety identity threshold mismatch"
        }

        val recordsJson = safety.getJSONObject("records")
        require(recordsJson.length() == expectedCodes.size) { "financial-safety record count mismatch" }

        val parsed = LinkedHashMap<String, FinancialSafetyRecord>(expectedCodes.size * 2)
        var pass = 0
        var fail = 0
        var hold = 0
        var notApplicable = 0

        val keys = recordsJson.keys()
        while (keys.hasNext()) {
            val code = keys.next()
            require(code.matches(Regex("[0-9A-Z]{6}"))) { "invalid financial-safety code $code" }
            require(code in expectedCodes) { "unknown financial-safety code $code" }
            require(!parsed.containsKey(code)) { "duplicate financial-safety code $code" }

            val row = recordsJson.getJSONObject(code)
            val status = runCatching { FinancialSafetyStatus.valueOf(row.getString("status")) }
                .getOrElse { throw IllegalArgumentException("invalid financial-safety status for $code") }
            val reason = row.getString("reason")
            val scope = row.optString("scope", "")
            val basis = row.optString("basis", "")
            require(reason.isNotBlank()) { "financial-safety reason missing for $code" }
            require(scope in setOf("", "CFS", "OFS")) { "financial-safety scope invalid for $code" }

            val debt = nullableFiniteDouble(row, "debt_to_equity_pct", code)
            val current = nullableFiniteDouble(row, "current_ratio_pct", code)
            val identity = nullableFiniteDouble(row, "identity_gap_pct", code)

            when (status) {
                FinancialSafetyStatus.PASS -> {
                    require(reason == "PASS") { "PASS reason mismatch for $code" }
                    require(scope in setOf("CFS", "OFS")) { "PASS scope missing for $code" }
                    require(debt != null && current != null && identity != null) { "PASS ratios missing for $code" }
                    require(debt <= DEBT_TO_EQUITY_MAX + 1e-9) { "PASS debt ratio violates policy for $code" }
                    require(current >= CURRENT_RATIO_MIN - 1e-9) { "PASS current ratio violates policy for $code" }
                    require(identity <= IDENTITY_TOLERANCE + 1e-9) { "PASS identity gap violates policy for $code" }
                    require(basis.isNotBlank()) { "PASS basis missing for $code" }
                    pass++
                }

                FinancialSafetyStatus.FAIL -> {
                    require(scope in setOf("CFS", "OFS")) { "FAIL scope missing for $code" }
                    require(basis.isNotBlank()) { "FAIL basis missing for $code" }
                    require(identity != null && identity <= IDENTITY_TOLERANCE + 1e-9) {
                        "FAIL requires a valid accounting identity for $code"
                    }
                    when (reason) {
                        "NONPOSITIVE_EQUITY" -> {
                            require(debt == null && current == null) { "nonpositive-equity derived ratios must be null for $code" }
                        }
                        "DEBT_TO_EQUITY_OVER_400" -> {
                            require(debt != null && current != null) { "debt FAIL ratios missing for $code" }
                            require(debt > DEBT_TO_EQUITY_MAX) { "debt FAIL does not exceed threshold for $code" }
                        }
                        "CURRENT_RATIO_UNDER_70" -> {
                            require(debt != null && current != null) { "current-ratio FAIL ratios missing for $code" }
                            require(debt <= DEBT_TO_EQUITY_MAX + 1e-9) { "current-ratio FAIL should have failed debt first for $code" }
                            require(current < CURRENT_RATIO_MIN) { "current-ratio FAIL does not violate threshold for $code" }
                        }
                        else -> throw IllegalArgumentException("unexpected financial-safety FAIL reason for $code: $reason")
                    }
                    fail++
                }

                FinancialSafetyStatus.HOLD -> {
                    when {
                        reason.startsWith("MISSING_") -> {
                            require(debt == null && current == null && identity == null) {
                                "missing-input HOLD ratios must be null for $code"
                            }
                        }
                        reason == "DART_NO_BALANCE_SHEET" -> {
                            require(scope.isBlank()) { "no-BS HOLD must not have scope for $code" }
                            require(basis.isBlank()) { "no-BS HOLD must not have basis for $code" }
                            require(debt == null && current == null && identity == null) {
                                "no-BS HOLD ratios must be null for $code"
                            }
                        }
                        reason == "NONPOSITIVE_ASSETS" -> {
                            require(debt == null && current == null && identity == null) {
                                "nonpositive-assets HOLD ratios must be null for $code"
                            }
                        }
                        reason == "ACCOUNTING_IDENTITY_MISMATCH" -> {
                            require(debt == null && current == null) { "identity HOLD debt/current ratios must be null for $code" }
                            require(identity == null || identity > IDENTITY_TOLERANCE) {
                                "identity HOLD does not exceed tolerance for $code"
                            }
                        }
                        reason == "NONPOSITIVE_CURRENT_LIABILITIES" -> {
                            require(debt != null && current == null && identity != null) {
                                "current-liabilities HOLD ratio shape invalid for $code"
                            }
                            require(identity <= IDENTITY_TOLERANCE + 1e-9) { "current-liabilities HOLD identity invalid for $code" }
                        }
                        reason == "NONFINITE_DERIVED_RATIO" -> {
                            // Upstream should normally reject/serialize no non-finite values before promotion.
                            // If this reason survives with finite JSON values, keep the HOLD state without inferring a replacement.
                        }
                        else -> throw IllegalArgumentException("unexpected financial-safety HOLD reason for $code: $reason")
                    }
                    hold++
                }

                FinancialSafetyStatus.NOT_APPLICABLE -> {
                    require(reason == "FINANCIAL_SECTOR_NOT_COMPARABLE") { "N/A reason mismatch for $code" }
                    require(scope.isBlank() && basis.isBlank()) { "N/A scope/basis must be empty for $code" }
                    require(debt == null && current == null && identity == null) { "N/A ratios must be null for $code" }
                    notApplicable++
                }
            }

            parsed[code] = FinancialSafetyRecord(
                issuerId = code,
                status = status,
                reasonCode = reason,
                scope = scope,
                debtToEquityPct = debt,
                currentRatioPct = current,
                accountingIdentityGapPct = identity,
                basis = basis,
            )
        }

        require(parsed.keys == expectedCodes) { "financial-safety identity set mismatch" }

        val coverage = safety.getJSONObject("coverage")
        require(coverage.getInt("pass") == pass) { "financial-safety PASS coverage mismatch" }
        require(coverage.getInt("fail") == fail) { "financial-safety FAIL coverage mismatch" }
        require(coverage.getInt("hold") == hold) { "financial-safety HOLD coverage mismatch" }
        require(coverage.getInt("not_applicable") == notApplicable) { "financial-safety N/A coverage mismatch" }
        require(coverage.getInt("total") == expectedCodes.size) { "financial-safety total coverage mismatch" }
        require(pass + fail + hold + notApplicable == expectedCodes.size) { "financial-safety coverage does not close" }

        return FinancialSafetySnapshot(
            policyVersion = POLICY_VERSION,
            snapshotDate = expectedSnapshotDate,
            source = source,
            sourceFile = sourceFile,
            passCount = pass,
            failCount = fail,
            holdCount = hold,
            notApplicableCount = notApplicable,
            records = parsed.toMap(),
        )
    }

    private fun nullableFiniteDouble(o: JSONObject, key: String, code: String): Double? {
        if (!o.has(key) || o.isNull(key)) return null
        val value = o.getDouble(key)
        require(value.isFinite()) { "$code $key is non-finite" }
        return value
    }
}

/** Process-local known-good Stage4 state. Date mismatch always returns empty. */
object FinancialSafetyRuntimeStore {
    @Volatile
    private var installed: FinancialSafetySnapshot? = null

    @Synchronized
    fun install(snapshot: FinancialSafetySnapshot) {
        require(snapshot.records.isNotEmpty()) { "cannot install empty financial-safety snapshot" }
        require(snapshot.records.all { (code, row) -> code == row.issuerId }) {
            "financial-safety record identity mismatch"
        }
        installed = snapshot.copy(records = snapshot.records.toMap())
    }

    @Synchronized
    fun clear() {
        installed = null
    }

    fun current(expectedSnapshotDate: String): FinancialSafetySnapshot? =
        installed?.takeIf { it.snapshotDate == expectedSnapshotDate }

    fun get(expectedSnapshotDate: String, issuerId: String): FinancialSafetyRecord? =
        current(expectedSnapshotDate)?.records?.get(issuerId)
}

object FinancialSafetyRepository {
    fun currentSnapshot(): FinancialSafetySnapshot? =
        FinancialSafetyRuntimeStore.current(StockRepository.quantSnapshotDate())

    fun get(issuerId: String): FinancialSafetyRecord? =
        FinancialSafetyRuntimeStore.get(StockRepository.quantSnapshotDate(), issuerId)

    fun getAll(): Map<String, FinancialSafetyRecord> =
        currentSnapshot()?.records.orEmpty()
}

/** Exact Stage5 band policy shared with build_final_candidates_v2.py. */
object ValuationBandPolicy {
    fun classify(metric: MetricValue): ValuationBand? =
        classify(metric.rawValue, metric.percentileScore)

    fun classify(trailingPer: Double?, percentile: Double?): ValuationBand? {
        if (trailingPer == null || percentile == null) return null
        if (!trailingPer.isFinite() || !percentile.isFinite()) return null
        if (trailingPer <= 0.0 || percentile !in 0.0..100.0) return null

        val code: String
        val label: String
        val short: String
        when {
            percentile >= 80.0 -> {
                code = "LOW_RELATIVE_PER"
                label = "시장 내 낮은 PER 구간"
                short = "낮은 PER"
            }
            percentile >= 60.0 -> {
                code = "BELOW_MEDIAN_PER"
                label = "시장 중앙값보다 낮은 PER 구간"
                short = "중앙값↓ PER"
            }
            percentile >= 40.0 -> {
                code = "MID_PER"
                label = "시장 중간 PER 구간"
                short = "중간 PER"
            }
            percentile >= 20.0 -> {
                code = "ABOVE_MEDIAN_PER"
                label = "시장 중앙값보다 높은 PER 구간"
                short = "중앙값↑ PER"
            }
            else -> {
                code = "HIGH_RELATIVE_PER"
                label = "시장 내 높은 PER 구간"
                short = "높은 PER"
            }
        }
        return ValuationBand(
            code = code,
            labelKo = label,
            shortLabelKo = short,
            percentile = percentile,
            changesRank = false,
        )
    }
}
